# Generated by Django 6.0.3 on 2026-03-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_advisorpost_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='buyer_location',
        ),
        migrations.RemoveField(
            model_name='order',
            name='buyer_phone',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
