# Generated by Django 6.0.3 on 2026-03-21 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_order_buyer_location_remove_order_buyer_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_location',
            field=models.CharField(default='Nairobi', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_phone',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.farmerprofile')),
            ],
        ),
    ]
