# Generated by Django 6.0.3 on 2026-03-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_orderitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/default.png', null=True, upload_to='profile_pics/'),
        ),
    ]
